### ISSUE TITLE
Multiple issues with project

### ISSUE THREAD

**Issue by ashuetawah** [microsoftgraph/uwp-csharp-meetingbot-sample#3]
I can download and open project. But there are multiple project related issues - 
1. Don't show me local device to debug/install option.
2. After adding project to different solution, I was able to install it locally, but does not open on Cortana command.
3. The default language is en-US. there is no instruction if that's not the case, how will it behave.
4. Cortana shows the calendar when asked for meeting rather opening app.
I am using VS 2017 Preview 15.5.0 preview 4.0 update on win10 Pro fall creator update.

**Comment by jasonjoh** [comment]
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. We apologize for any inconvenience.
